/*
 * This file is generated by jOOQ.
 */
package com.kopivad.testingsystem.model.db.tables.records;


import com.kopivad.testingsystem.model.db.tables.QuizResults;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizResultsRecord extends UpdatableRecordImpl<QuizResultsRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1111523603;

    /**
     * Setter for <code>testing_system.quiz_results.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>testing_system.quiz_results.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return QuizResults.QUIZ_RESULTS.ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public QuizResultsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QuizResultsRecord values(Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizResultsRecord
     */
    public QuizResultsRecord() {
        super(QuizResults.QUIZ_RESULTS);
    }

    /**
     * Create a detached, initialised QuizResultsRecord
     */
    public QuizResultsRecord(Long id) {
        super(QuizResults.QUIZ_RESULTS);

        set(0, id);
    }
}
