/*
 * This file is generated by jOOQ.
 */
package com.kopivad.testingsystem.model.db.tables.records;


import com.kopivad.testingsystem.model.db.tables.QuizSessions;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizSessionsRecord extends UpdatableRecordImpl<QuizSessionsRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = 829539007;

    /**
     * Setter for <code>testing_system.quiz_sessions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>testing_system.quiz_sessions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>testing_system.quiz_sessions.quiz_id</code>.
     */
    public void setQuizId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>testing_system.quiz_sessions.quiz_id</code>.
     */
    public Long getQuizId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>testing_system.quiz_sessions.user_id</code>.
     */
    public void setUserId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>testing_system.quiz_sessions.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return QuizSessions.QUIZ_SESSIONS.ID;
    }

    @Override
    public Field<Long> field2() {
        return QuizSessions.QUIZ_SESSIONS.QUIZ_ID;
    }

    @Override
    public Field<Long> field3() {
        return QuizSessions.QUIZ_SESSIONS.USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getQuizId();
    }

    @Override
    public Long component3() {
        return getUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getQuizId();
    }

    @Override
    public Long value3() {
        return getUserId();
    }

    @Override
    public QuizSessionsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public QuizSessionsRecord value2(Long value) {
        setQuizId(value);
        return this;
    }

    @Override
    public QuizSessionsRecord value3(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public QuizSessionsRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizSessionsRecord
     */
    public QuizSessionsRecord() {
        super(QuizSessions.QUIZ_SESSIONS);
    }

    /**
     * Create a detached, initialised QuizSessionsRecord
     */
    public QuizSessionsRecord(Long id, Long quizId, Long userId) {
        super(QuizSessions.QUIZ_SESSIONS);

        set(0, id);
        set(1, quizId);
        set(2, userId);
    }
}
