/*
 * This file is generated by jOOQ.
 */
package com.kopivad.testingsystem.model.db;


import com.kopivad.testingsystem.model.db.tables.*;
import com.kopivad.testingsystem.model.db.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>testing_system</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AnswersRecord, Long> IDENTITY_ANSWERS = Identities0.IDENTITY_ANSWERS;
    public static final Identity<QuestionsRecord, Long> IDENTITY_QUESTIONS = Identities0.IDENTITY_QUESTIONS;
    public static final Identity<QuizResultsRecord, Long> IDENTITY_QUIZ_RESULTS = Identities0.IDENTITY_QUIZ_RESULTS;
    public static final Identity<QuizzesRecord, Long> IDENTITY_QUIZZES = Identities0.IDENTITY_QUIZZES;
    public static final Identity<UserResponcesRecord, Long> IDENTITY_USER_RESPONCES = Identities0.IDENTITY_USER_RESPONCES;
    public static final Identity<UsersRecord, Long> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AnswersRecord> KEY_ANSWERS_PRIMARY = UniqueKeys0.KEY_ANSWERS_PRIMARY;
    public static final UniqueKey<QuestionsRecord> KEY_QUESTIONS_PRIMARY = UniqueKeys0.KEY_QUESTIONS_PRIMARY;
    public static final UniqueKey<QuizResultsRecord> KEY_QUIZ_RESULTS_PRIMARY = UniqueKeys0.KEY_QUIZ_RESULTS_PRIMARY;
    public static final UniqueKey<QuizzesRecord> KEY_QUIZZES_PRIMARY = UniqueKeys0.KEY_QUIZZES_PRIMARY;
    public static final UniqueKey<UserResponcesRecord> KEY_USER_RESPONCES_PRIMARY = UniqueKeys0.KEY_USER_RESPONCES_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AnswersRecord, QuestionsRecord> FK3ERW1A3T0R78ST8TY27X6V3G1 = ForeignKeys0.FK3ERW1A3T0R78ST8TY27X6V3G1;
    public static final ForeignKey<QuestionsRecord, QuizzesRecord> FKN3GVCO4B0KEWXC0BYWF1IGFMS = ForeignKeys0.FKN3GVCO4B0KEWXC0BYWF1IGFMS;
    public static final ForeignKey<QuizzesRecord, UsersRecord> FKA2RODABLX8MHCE3BDAJ19EQHE = ForeignKeys0.FKA2RODABLX8MHCE3BDAJ19EQHE;
    public static final ForeignKey<UserResponcesRecord, AnswersRecord> FKT4X7J4GV9GNVW9EQ16VQFQI46 = ForeignKeys0.FKT4X7J4GV9GNVW9EQ16VQFQI46;
    public static final ForeignKey<UserResponcesRecord, QuestionsRecord> FK323KVT7ONI5T0B0TR570YYN9T = ForeignKeys0.FK323KVT7ONI5T0B0TR570YYN9T;
    public static final ForeignKey<UserRolesRecord, UsersRecord> FKHFH9DX7W3UBF1CO1VDEV94G3F = ForeignKeys0.FKHFH9DX7W3UBF1CO1VDEV94G3F;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AnswersRecord, Long> IDENTITY_ANSWERS = Internal.createIdentity(Answers.ANSWERS, Answers.ANSWERS.ID);
        public static Identity<QuestionsRecord, Long> IDENTITY_QUESTIONS = Internal.createIdentity(Questions.QUESTIONS, Questions.QUESTIONS.ID);
        public static Identity<QuizResultsRecord, Long> IDENTITY_QUIZ_RESULTS = Internal.createIdentity(QuizResults.QUIZ_RESULTS, QuizResults.QUIZ_RESULTS.ID);
        public static Identity<QuizzesRecord, Long> IDENTITY_QUIZZES = Internal.createIdentity(Quizzes.QUIZZES, Quizzes.QUIZZES.ID);
        public static Identity<UserResponcesRecord, Long> IDENTITY_USER_RESPONCES = Internal.createIdentity(UserResponces.USER_RESPONCES, UserResponces.USER_RESPONCES.ID);
        public static Identity<UsersRecord, Long> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AnswersRecord> KEY_ANSWERS_PRIMARY = Internal.createUniqueKey(Answers.ANSWERS, "KEY_answers_PRIMARY", Answers.ANSWERS.ID);
        public static final UniqueKey<QuestionsRecord> KEY_QUESTIONS_PRIMARY = Internal.createUniqueKey(Questions.QUESTIONS, "KEY_questions_PRIMARY", Questions.QUESTIONS.ID);
        public static final UniqueKey<QuizResultsRecord> KEY_QUIZ_RESULTS_PRIMARY = Internal.createUniqueKey(QuizResults.QUIZ_RESULTS, "KEY_quiz_results_PRIMARY", QuizResults.QUIZ_RESULTS.ID);
        public static final UniqueKey<QuizzesRecord> KEY_QUIZZES_PRIMARY = Internal.createUniqueKey(Quizzes.QUIZZES, "KEY_quizzes_PRIMARY", Quizzes.QUIZZES.ID);
        public static final UniqueKey<UserResponcesRecord> KEY_USER_RESPONCES_PRIMARY = Internal.createUniqueKey(UserResponces.USER_RESPONCES, "KEY_user_responces_PRIMARY", UserResponces.USER_RESPONCES.ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, "KEY_users_PRIMARY", Users.USERS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AnswersRecord, QuestionsRecord> FK3ERW1A3T0R78ST8TY27X6V3G1 = Internal.createForeignKey(com.kopivad.testingsystem.model.db.Keys.KEY_QUESTIONS_PRIMARY, Answers.ANSWERS, "FK3erw1a3t0r78st8ty27x6v3g1", Answers.ANSWERS.QUESTION_ID);
        public static final ForeignKey<QuestionsRecord, QuizzesRecord> FKN3GVCO4B0KEWXC0BYWF1IGFMS = Internal.createForeignKey(com.kopivad.testingsystem.model.db.Keys.KEY_QUIZZES_PRIMARY, Questions.QUESTIONS, "FKn3gvco4b0kewxc0bywf1igfms", Questions.QUESTIONS.QUIZ_ID);
        public static final ForeignKey<QuizzesRecord, UsersRecord> FKA2RODABLX8MHCE3BDAJ19EQHE = Internal.createForeignKey(com.kopivad.testingsystem.model.db.Keys.KEY_USERS_PRIMARY, Quizzes.QUIZZES, "FKa2rodablx8mhce3bdaj19eqhe", Quizzes.QUIZZES.USER_ID);
        public static final ForeignKey<UserResponcesRecord, AnswersRecord> FKT4X7J4GV9GNVW9EQ16VQFQI46 = Internal.createForeignKey(com.kopivad.testingsystem.model.db.Keys.KEY_ANSWERS_PRIMARY, UserResponces.USER_RESPONCES, "FKt4x7j4gv9gnvw9eq16vqfqi46", UserResponces.USER_RESPONCES.ANSWER_ID);
        public static final ForeignKey<UserResponcesRecord, QuestionsRecord> FK323KVT7ONI5T0B0TR570YYN9T = Internal.createForeignKey(com.kopivad.testingsystem.model.db.Keys.KEY_QUESTIONS_PRIMARY, UserResponces.USER_RESPONCES, "FK323kvt7oni5t0b0tr570yyn9t", UserResponces.USER_RESPONCES.QUESTION_ID);
        public static final ForeignKey<UserRolesRecord, UsersRecord> FKHFH9DX7W3UBF1CO1VDEV94G3F = Internal.createForeignKey(com.kopivad.testingsystem.model.db.Keys.KEY_USERS_PRIMARY, UserRoles.USER_ROLES, "FKhfh9dx7w3ubf1co1vdev94g3f", UserRoles.USER_ROLES.USER_ID);
    }
}
