/*
 * This file is generated by jOOQ.
 */
package com.kopivad.testingsystem.model.db;


import com.kopivad.testingsystem.model.db.tables.Answers;
import com.kopivad.testingsystem.model.db.tables.Questions;
import com.kopivad.testingsystem.model.db.tables.Quizzes;
import com.kopivad.testingsystem.model.db.tables.UserResponces;
import com.kopivad.testingsystem.model.db.tables.UserRoles;
import com.kopivad.testingsystem.model.db.tables.Users;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestingSystem extends SchemaImpl {

    private static final long serialVersionUID = 424071441;

    /**
     * The reference instance of <code>testing_system</code>
     */
    public static final TestingSystem TESTING_SYSTEM = new TestingSystem();

    /**
     * The table <code>testing_system.answers</code>.
     */
    public final Answers ANSWERS = com.kopivad.testingsystem.model.db.tables.Answers.ANSWERS;

    /**
     * The table <code>testing_system.questions</code>.
     */
    public final Questions QUESTIONS = com.kopivad.testingsystem.model.db.tables.Questions.QUESTIONS;

    /**
     * The table <code>testing_system.quizzes</code>.
     */
    public final Quizzes QUIZZES = com.kopivad.testingsystem.model.db.tables.Quizzes.QUIZZES;

    /**
     * The table <code>testing_system.user_responces</code>.
     */
    public final UserResponces USER_RESPONCES = com.kopivad.testingsystem.model.db.tables.UserResponces.USER_RESPONCES;

    /**
     * The table <code>testing_system.user_roles</code>.
     */
    public final UserRoles USER_ROLES = com.kopivad.testingsystem.model.db.tables.UserRoles.USER_ROLES;

    /**
     * The table <code>testing_system.users</code>.
     */
    public final Users USERS = com.kopivad.testingsystem.model.db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private TestingSystem() {
        super("testing_system", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Answers.ANSWERS,
            Questions.QUESTIONS,
            Quizzes.QUIZZES,
            UserResponces.USER_RESPONCES,
            UserRoles.USER_ROLES,
            Users.USERS);
    }
}
